services:
  subspace-trmnl:
    init: true
    build: ./
    image: subspace-trmnl:dev
    container_name: subspace-trmnl-dev
    restart: always
    ports:
      - 9595:9595
    env_file: .env
    environment:
      TRMNL_DB_PATH: /opt/api/subspace-db/trmnl.sqlite
    volumes:
      - ./data_dev:/opt/api/subspace-db
    networks:
      - proxy
      - api
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.subspace-trmnl.rule=Host(`trmnl.subtype.space`)'
      - 'traefik.http.routers.subspace-trmnl.entrypoints=websecure'
      - 'traefik.http.routers.subspace-trmnl.tls=true'
      - 'traefik.http.routers.subspace-trmnl.tls.certresolver=cloudflare'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.subspace-trmnl.middlewares=secureHeaders@file, generic-csp@file'

networks:
  proxy:
    external: true
  api:
    external: true