services:
  subspace-api:
    build: ./
    image: subspace-api:dev
    container_name: subspace-api-dev
    restart: always
    ports:
      - 9595:9595
    env_file: .env
    environment:
      TRMNL_DB_PATH: /opt/api/subspace-db/trmnl.sqlite
    volumes:
      - ./data_dev:/opt/api/subspace-db
    networks:
      - proxy
      - api
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.subspace-api.rule=Host(`api.subtype.space`)'
      - 'traefik.http.routers.subspace-api.entrypoints=websecure'
      - 'traefik.http.routers.subspace-api.tls=true'
      - 'traefik.http.routers.subspace-api.tls.certresolver=cloudflare'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.subspace-api.middlewares=secureHeaders@file, generic-csp@file'

networks:
  proxy:
    external: true
  api:
    external: true